import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "../../../../lib/admin-auth";
import { getAdminCustomer } from "../../../../lib/admin/queries/customers";

export default async function CustomerDetailPage({ params }: { params: Promise<{ email: string }> }) {
  await requireAdmin();
  const customer = await getAdminCustomer(decodeURIComponent((await params).email));
  if (!customer) notFound();
  return <section className="@container/main flex flex-1 flex-col gap-6 px-4 py-6 lg:px-6"><div><Link href="/admin/customers" className="text-sm underline">Back to customers</Link><h1 className="mt-3 text-xl font-semibold">{customer.name}</h1><p className="text-sm text-muted-foreground">{customer.email}{customer.phone ? ` · ${customer.phone}` : ""}</p></div><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-lg border p-4"><p className="text-sm text-muted-foreground">Orders</p><p className="mt-2 text-2xl font-semibold">{customer.orders.length}</p></div><div className="rounded-lg border p-4"><p className="text-sm text-muted-foreground">Order value</p><p className="mt-2 text-2xl font-semibold">${customer.totalSpent.toFixed(2)}</p></div><div className="rounded-lg border p-4"><p className="text-sm text-muted-foreground">Account</p><p className="mt-2 text-sm font-medium">{customer.registeredAt ? `Registered ${new Date(customer.registeredAt).toLocaleDateString("en-GB")}` : "Guest checkout"}</p></div></div><div className="overflow-hidden rounded-lg border"><table className="w-full text-sm"><thead className="bg-muted text-left"><tr><th className="p-3">Order</th><th className="p-3">Items</th><th className="p-3">Total</th><th className="p-3">Status</th><th className="p-3">Date</th></tr></thead><tbody>{customer.orders.map((order) => <tr key={order.id} className="border-t"><td className="p-3"><Link href={`/admin/orders/${order.id}`} className="font-medium underline">{order.orderNumber}</Link></td><td className="p-3">{order.items.reduce((total, item) => total + item.quantity, 0)}</td><td className="p-3">${Number(order.totalAmount).toFixed(2)}</td><td className="p-3 capitalize">{order.status}</td><td className="p-3">{order.createdAt ? new Date(order.createdAt).toLocaleDateString("en-GB") : "—"}</td></tr>)}</tbody></table></div></section>;
}
