"use client";
import { useState, useTransition } from "react";
import { saveAddress, saveProfile, setDefaultAddress, deleteAddress, linkVerifiedGuestOrders } from "@/app/actions/account";

type Address = { id: number; label: string; recipientName: string; phone: string; street: string; city: string; state: string; postalCode: string | null; isDefault: boolean };
export function AccountDashboard({ account, profile, addresses, orderCount }: { account: { name: string; email: string; phone: string | null }; profile: { marketingEmailOptIn: boolean; marketingWhatsappOptIn: boolean } | null; addresses: Address[]; orderCount: number }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState(""); const [showAddress, setShowAddress] = useState(false);
  function run(task: () => Promise<void>, text: string) { startTransition(async () => { try { await task(); setMessage(text); } catch (error) { setMessage(error instanceof Error ? error.message : "Something went wrong."); } }); }
  return <div className="mx-auto max-w-6xl px-5 py-12 sm:px-10 lg:py-16"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[#d3146d]">Your account</p><h1 className="mt-4 text-5xl font-medium tracking-[-.06em] sm:text-7xl">Hello, {account.name.split(" ")[0]}.</h1><div className="mt-5 flex flex-wrap items-center gap-4"><p className="text-sm text-black/65">{orderCount} order{orderCount === 1 ? "" : "s"} linked to this account.</p><button onClick={() => run(linkVerifiedGuestOrders, "Previous guest orders matching this email have been linked.")} className="text-xs font-semibold uppercase tracking-[.12em] text-[#d3146d] underline">Link earlier guest orders</button></div>{message && <p className="mt-6 border-l-4 border-[#d3146d] bg-[#f8dbe9] px-4 py-3 text-sm">{message}</p>}
  <div className="mt-12 grid gap-8 lg:grid-cols-2"><section className="border border-black p-6 sm:p-8"><h2 className="text-2xl font-medium">Profile</h2><form className="mt-6 space-y-5" onSubmit={(e) => { e.preventDefault(); const form = new FormData(e.currentTarget); run(() => saveProfile({ name: String(form.get("name")), phone: String(form.get("phone")), marketingEmailOptIn: form.get("marketingEmailOptIn") === "on", marketingWhatsappOptIn: form.get("marketingWhatsappOptIn") === "on" }), "Your profile has been saved."); }}><label className="block text-sm">Full name<input name="name" defaultValue={account.name} className="mt-2 w-full border border-black px-3 py-3" /></label><label className="block text-sm">Email address<input disabled value={account.email} className="mt-2 w-full border border-black bg-black/5 px-3 py-3 text-black/60" /></label><label className="block text-sm">Phone<input name="phone" defaultValue={account.phone || ""} className="mt-2 w-full border border-black px-3 py-3" /></label><label className="flex gap-3 text-sm"><input name="marketingEmailOptIn" type="checkbox" defaultChecked={profile?.marketingEmailOptIn} /> Email me about new pieces and offers</label><label className="flex gap-3 text-sm"><input name="marketingWhatsappOptIn" type="checkbox" defaultChecked={profile?.marketingWhatsappOptIn} /> Send updates through WhatsApp</label><button disabled={pending} className="bg-black px-5 py-3 text-xs font-semibold uppercase tracking-[.13em] text-white hover:bg-[#d3146d]">Save profile</button></form></section>
  <section className="border border-black p-6 sm:p-8"><div className="flex items-center justify-between gap-4"><h2 className="text-2xl font-medium">Delivery addresses</h2><button onClick={() => setShowAddress(!showAddress)} className="text-xs font-semibold uppercase tracking-[.13em] text-[#d3146d] underline">{showAddress ? "Close" : "Add address"}</button></div>{addresses.length === 0 && <p className="mt-6 text-sm text-black/60">Save an address to check out faster next time.</p>}<div className="mt-6 space-y-4">{addresses.map((address) => <div key={address.id} className="border border-black/20 p-4 text-sm"><div className="flex justify-between gap-3"><p className="font-medium">{address.label} {address.isDefault && <span className="ml-2 text-[10px] uppercase tracking-[.12em] text-[#d3146d]">Default</span>}</p><button onClick={() => run(() => deleteAddress(address.id), "Address removed.")} className="text-xs underline">Remove</button></div><p className="mt-2 text-black/65">{address.recipientName}<br />{address.street}<br />{address.city}, {address.state}<br />{address.phone}</p>{!address.isDefault && <button onClick={() => run(() => setDefaultAddress(address.id), "Default address updated.")} className="mt-3 text-xs font-semibold uppercase tracking-[.12em] text-[#d3146d] underline">Make default</button>}</div>)}</div>{showAddress && <form className="mt-6 grid gap-4 border-t border-black pt-6 sm:grid-cols-2" onSubmit={(e) => { e.preventDefault(); const form = new FormData(e.currentTarget); run(() => saveAddress({ label: String(form.get("label")), recipientName: String(form.get("recipientName")), phone: String(form.get("phone")), street: String(form.get("street")), city: String(form.get("city")), state: String(form.get("state")), postalCode: String(form.get("postalCode")), isDefault: form.get("isDefault") === "on" }), "Address saved."); e.currentTarget.reset(); setShowAddress(false); }}><input name="label" required placeholder="Address label (e.g. Home)" className="border border-black px-3 py-3"/><input name="recipientName" required placeholder="Recipient name" className="border border-black px-3 py-3"/><input name="phone" required placeholder="Phone number" className="border border-black px-3 py-3"/><input name="street" required placeholder="Street address" className="border border-black px-3 py-3 sm:col-span-2"/><input name="city" required placeholder="City" className="border border-black px-3 py-3"/><input name="state" required placeholder="State" className="border border-black px-3 py-3"/><input name="postalCode" placeholder="Postal code (optional)" className="border border-black px-3 py-3"/><label className="flex items-center gap-2 text-sm"><input name="isDefault" type="checkbox" defaultChecked={addresses.length === 0}/> Make default</label><button disabled={pending} className="bg-[#d3146d] px-5 py-3 text-xs font-semibold uppercase tracking-[.13em] text-white sm:w-fit">Save address</button></form>}</section></div></div>;
}
