"use client";

import { useState } from "react";

type CustomerOrder = { id: string; orderNumber: string; createdAt: Date | null; status: string; totalAmount: string; items: { id: string; productName: string; productImage: string | null; quantity: number; unitPrice: string; totalPrice: string; size: string | null }[] };

export function OrderHistory({ orders }: { orders: CustomerOrder[] }) {
  const [openOrder, setOpenOrder] = useState<string | null>(null);
  return <section className="mx-auto max-w-6xl px-5 pb-16 sm:px-10"><h2 className="border-b border-black pb-4 text-2xl font-medium">Order history</h2><div className="mt-5 space-y-4">{orders.map((order) => { const isOpen = openOrder === order.id; return <article key={order.id} className="border border-black/20 bg-white"><button type="button" onClick={() => setOpenOrder(isOpen ? null : order.id)} aria-expanded={isOpen} className="flex w-full flex-wrap items-center justify-between gap-4 p-5 text-left transition-colors hover:bg-[#f8dbe9]"><div><p className="font-medium">{order.orderNumber}</p><p className="mt-1 text-sm text-black/55">{order.createdAt?.toLocaleDateString("en-NG", { dateStyle: "medium" })}</p></div><div className="flex items-center gap-5 text-sm"><span className="capitalize">{order.status}</span><span className="font-medium">₦{Number(order.totalAmount).toLocaleString("en-NG")}</span><span className="text-xs font-semibold uppercase tracking-[.12em] text-[#d3146d]">{isOpen ? "Hide items" : "View items"}</span></div></button>{isOpen && <div className="border-t border-black/15 px-5 py-4"><div className="divide-y divide-black/10">{order.items.map((item) => <div key={item.id} className="flex items-center gap-4 py-4"><div className="h-16 w-14 shrink-0 bg-[#f8dbe9]">{item.productImage && <img src={item.productImage} alt="" className="h-full w-full object-cover" />}</div><div className="min-w-0 flex-1"><p className="font-medium">{item.productName}</p><p className="mt-1 text-xs text-black/55">Quantity {item.quantity}{item.size ? ` · Size ${item.size}` : ""}</p></div><p className="text-sm font-medium">₦{Number(item.totalPrice).toLocaleString("en-NG")}</p></div>)}</div><div className="flex justify-between border-t border-black/15 pt-4 text-sm font-medium"><span>Order total</span><span>₦{Number(order.totalAmount).toLocaleString("en-NG")}</span></div></div>}</article>; })}</div></section>;
}
